#! /bin/sh
# kcminputrc Mouse cursorTheme 'breeze_cursors'
kcminputrc_mouse_cursortheme=Bibata_Pink
# kcminputrc Mouse cursorSize ''
kcminputrc_mouse_cursorsize=0
# ksplashrc KSplash Theme Breeze
ksplashrc_ksplash_theme=Sweet
# ksplashrc KSplash Engine KSplashQML
ksplashrc_ksplash_engine=KSplashQML
# kdeglobals KScreen ScaleFactor ''
kdeglobals_kscreen_scalefactor=1
# kdeglobals KScreen ScreenScaleFactors ''
kdeglobals_kscreen_screenscalefactors='eDP-1=1;HDMI-1=1;DP-1=1;HDMI-2=1;'
# kcmfonts General forceFontDPI 0
kcmfonts_general_forcefontdpi=0
